export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    price: 450000,
    stock: 12,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://picsum.photos/seed/headphones/300/200",
  },
  {
    id: 2,
    name: "Smart Watch",
    slug: "smart-watch",
    price: 650000,
    stock: 8,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://picsum.photos/seed/watch/300/200",
  },
  {
    id: 3,
    name: "Mechanical Keyboard",
    slug: "mechanical-keyboard",
    price: 750000,
    stock: 10,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://picsum.photos/seed/keyboard/300/200",
  },
  {
    id: 4,
    name: "Wireless Mouse",
    slug: "wireless-mouse",
    price: 250000,
    stock: 15,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://picsum.photos/seed/mouse/300/200",
  },
  {
    id: 5,
    name: "Oversized Hoodie",
    slug: "oversized-hoodie",
    price: 180000,
    stock: 20,
    category: 2,
    category_name: "Fashion",
    rating: 5,
    img: "https://picsum.photos/seed/hoodie/300/200",
  },
  {
    id: 6,
    name: "Canvas Sneakers",
    slug: "canvas-sneakers",
    price: 320000,
    stock: 9,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://picsum.photos/seed/sneakers/300/200",
  },
  {
    id: 7,
    name: "Face Wash",
    slug: "face-wash",
    price: 85000,
    stock: 25,
    category: 3,
    category_name: "Kecantikan",
    rating: 4,
    img: "https://picsum.photos/seed/facewash/300/200",
  },
  {
    id: 8,
    name: "Moisturizer",
    slug: "moisturizer",
    price: 120000,
    stock: 18,
    category: 3,
    category_name: "Kecantikan",
    rating: 5,
    img: "https://picsum.photos/seed/moisturizer/300/200",
  },
];